### ISSUE TITLE
Custom fields in OR clause results in "Invalid field" error

### ISSUE THREAD

**Issue by bhahumanists** [civicrm/org.civicrm.api4#110]
A search like this:

![image](https://user-images.githubusercontent.com/5374634/54842058-c1cb3100-4cc8-11e9-84af-80bda4b8310e.png)

results in "Invalid field '[...]' in where clause." The custom field works fine outside of the OR clause.

This is on 4.3.0.

**Comment by colemanw** [comment]
I've committed a fix with a test:  f2a2edb
