### ISSUE TITLE
apiv4 regression

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.api4#123]
I have the current apiv4 & CLE against the 5.13 & just recenty did a git pull - getting the last ? week or 2 of changes & started getting fatals on contact edit screen with CLE enabled. This is likely to be something transitory but just flagging we should test CLE with apiv4 for each release tarball until apiv4 development becomes less active (for now I've gone back to apiv4 from about a week ago & it's working)

**Comment by colemanw** [comment]
What is the fatal?

**Comment by eileenmcnaughton** [comment]
The authorize is not working - honestly if it works for you I wouldn't dig too much just yet - my main worry right now is that we check our 5.13 release works with CLE with the api version it ships with because I did a bit of juggling (actually I hacked out the authorize call) but that's because I'm just trying to get something demo-able at the moment & not reviewable just yet

**Comment by colemanw** [comment]
Err, I think that's a real problem, caused by #115 - I'll add more info to that PR.

**Comment by colemanw** [comment]
See https://lab.civicrm.org/dev/core/issues/920
