### ISSUE TITLE
Activity 'Date' Custom Field ignores the time

### ISSUE THREAD

**Issue by mlutfy** [civicrm/org.civicrm.api4#129]
To reproduce:

* Create a new custom group for Activities
* Add a field of type=Date, with a time field included (I used the 24h format).

![Capture d’écran de 2019-05-06 12-35-08](https://user-images.githubusercontent.com/254741/57239992-6f856b80-6ffb-11e9-829a-3f029d1df9a1.png)

Notice how the API4 explorer does not display the time field for the custom field, as it does for the `activity_date_time` field:

![Capture d’écran de 2019-05-06 12-34-20](https://user-images.githubusercontent.com/254741/57239944-4ebd1600-6ffb-11e9-8be3-eae5f6450231.png)

The resulting SQL query does not have the time either. This makes it difficult to find activities at a given time (I use this to detect whether a contact is busy or not for scheduling meetings).

**Comment by colemanw** [comment]
@mlutfy please try #130
