### ISSUE TITLE
Design Principles: add "Secure"

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#16]
seems worth adding this motherhood statement?

worth unpacking a bit more what `secure` means and how to make clear to both internal external coders their security privilege context?

**Comment by JoeMurray** [comment]
What's the difference between security privilege context and the ACL permissions of the current user?

Making CiviCRM secure has many levels and aspects. I wouldn't aim to deal so much with the security of code in APIv4 (we need that everywhere) as the security related specifically to the design of the API.
