### ISSUE TITLE
Contact::update() clears contact subtype

### ISSUE THREAD

**Issue by mattwire** [civicrm/org.civicrm.api4#160]
Using version 4.5.0 (master) + CiviCRM master.

This resets contact subtype to null!  (There are two custom values being set here as well which do get set).
```
    $results = \Civi\Api4\Contact::update()
      ->addWhere('id', '=', $contact['id'])
      ->addValue('Documents.Document_Type', $this->mapDocumentType($params))
      ->addValue('Documents.Date_Uploaded', $uploadDate)
      ->execute();
```

**Comment by colemanw** [comment]
Turns out the core BAO is doing this on purpose. I really don't know what to say about this piece of work:

https://github.com/civicrm/civicrm-core/blob/5.14/CRM/Contact/BAO/Contact.php#L143-L147

**Comment by colemanw** [comment]
@mattwire can you review https://github.com/civicrm/civicrm-core/pull/14492
