### ISSUE TITLE
Requirement: Pagable

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#20]
Paging is useful for rapid UI pages, and also to facilitate batch operation.

So it seems useful to think about 3 levels of entity lists:

* `simple` bag of IDs `[57, 108, 130]`
* `sortable` (therefore pageable) list - which has the ID and a single field that enables sorting
* `decorated` lists with extra fields from same enitity or foreign tables

Architecture needs to start with `simple` lists to allow  Boolean "set" operations (union, intersection, subraction)/(OR/AND/NOT) and then once Boolean phase is over the list maybe made sortable.

I'm still not sure what the above means practically but wanted to start organising thoughts...

then finally the list is decorated on a "page by page" basis

both of the first 2 levels will benefit form caching

**Comment by JoeMurray** [comment]
IIRC the current DBDataObject library is not well purposed for doing batch work. Doctrine 2 also has some issues http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/batch-processing.html

**Comment by colemanw** [comment]
We have `limit` and `offset`, I think that's about all we're going to get in api4.
