### ISSUE TITLE
It should be noted someplace here and on the civi extensions page that this has been rolled into core with 5.19

### ISSUE THREAD

**Issue by Paul-Tahoe** [civicrm/org.civicrm.api4#210]
I'm testing an civi upgrade and hadn't noticed api 4 is now rolled into core.  I saw it saying it was obsolete on the extension menu in civi.  Wondered why and went to the extension page, https://civicrm.org/extensions/api4 and then the github.  It seems like on the releases and compatibility matrix on that page it should say something about being part of civi 5.19+.  Probably something as well on github.

**Comment by colemanw** [comment]
Done.
