### ISSUE TITLE
commit to getting rid of getsingle

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#23]
just tidying up the test file and found this comment.

is there a strong view? shall we lock it in? then just needs documenting in the readme?

```
    $call = Participant::get()                                                  
      ->setLimit(2);                                                            
    $result = $call->execute();                                                 
    $this->assertEquals(2, count($result),                                      
      "did not get back two records as expected");                              
    // Here's a convenient way to get the first result - maybe a replacement for getsingle                                                                      
    // Rationale for ditching getsingle - it's an output format & not a real action                                                                             
    // and output transformations would be better handled by the $result object.
    $firstResult = $result->first();                                            
    $this->assertEquals(1, $firstResult['id']);                                 
```

**Comment by eileenmcnaughton** [comment]
I personally love getsingle :-) But I think it is negotiable in api v4 if the same thing can be achieved pretty easily another way 

$result = $call->execute()->first();

is still a fairly short piece of code.

I also make heavy use of the fact getsingle throws an exception if not exactly one result is thrown - I would like to see some suggestions around that - 

$call = Participant::get()
->setExpectation(1);

might be an alternate format?

**Comment by colemanw** [comment]
I added a 4th param to `civicrm_api` in javascript and php which provides the same values as `getsingle` and `sequential` plus can do a lot of other things as well (index by other fields or return the nth result).
