### ISSUE TITLE
specify contribution.get requirement

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#32]
coming from discussion #29 

API 4.alpha.0.0.0.1 is likely to be `clean & fast` contribution.get action...

need to specify the specific requirements (by contact? by campaign? what is good about v3 and needs to come over? etc

any other general requirements be good to know too

**Comment by eileenmcnaughton** [comment]
@ErichBSchulz the good thing about api v3 is the unit tests.  In general you should assume that anything good in api v3 is covered in the test contract. That doesn't mean that everything in the test contract is good. 

The initial assumption is that it will be identical code-wise to the existing participant.get. However, when porting the tests some things may reveal themselves as warranting further consideration.

The api code itself should be as lean as possible. The wrapper & generic code should have all the magic

**Comment by ErichBSchulz** [comment]
is this a typo? "existing participant.get" - did you mean "contribution.get"?

**Comment by eileenmcnaughton** [comment]
I mean - the participant.get has already been ported to apiv4 & is the basis
