### ISSUE TITLE
How much SQL should an API expose to internal and external consumers?

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/org.civicrm.api4#41]
For CiviCRM using its own API internally as a query builder, I think #10, #11, #31 etc make a fair bit of sense.

When we expose the API to external clients, I feel uncomfortable about our API being an SQL builder, because we're exposing a lot more surface to attackers to pry on when we provide direct SQLisms such as LIKE, OR, AND, NOT. (Compared with API queries being limited to simple entity filters by matching parameter.)

I understand that historically CiviCRM has exposed a lot of SQLism, that the application is deeply SQL-ish, and that not offering this would be a big challenge. But I want to check in and see whether we can approach this in a way which improves our security.

Here I see CiviCRM's API trying to do things other APIs typically don't, which makes me wonder if a unique approach is a good idea. Are there good examples of other web APIs which expose SQL params so directly?

For me, this raises the question of whether building the API for dual-usage (internal and external) places conflicting demands on the resulting tool.

**Comment by jackrabbithanna** [comment]
as always I think about how Drupal does things.  So lets take EntityFieldQuery().  What you have here an api that is basically a wrapper around construction of a SelectQuery object.  The the SelectQuery object constructs the actual SQL and executes it.  So there are two layers.  Developers can use the EntityFieldQuery object methods as provided, or they can TAG the query and make customizations to the actual SelectQuery object. I know this isn't an exact parallel of the CiviCRM API situation, but its food for thought.  How many security problems would be avoidable when using something like SelectQuery.

**Comment by xurizaemon** [comment]
That's the internal case, and currently api4 fluent queries are looking pretty SelectQuery-ish to me. 👍 

What will that look like when it's being consumed externally over HTTP, rather than by an extension with access to Civi's internal methods?

**Comment by jackrabbithanna** [comment]
Maybe there's a case for having external API calls limited in some fashion, basically only have the 'public' methods available for use, and for the internal case you have something more powerful/customizable.  Trying to do everything consistently with one API is probably quite a bit more difficult.  The idea of a external API allowing any direct SQL manipulation by any means poses some major security headaches

**Comment by ErichBSchulz** [comment]
You're smelling :dragon: s @xurizaemon ??

re "Are there good examples of other web APIs which expose SQL params so directly?" - I guess I kind of agree that the exposing the `field-operator-value` triples contradicts the goal of being "business process" orientated - but it is the pattern of API 3 and all the code is written to support this pattern - are you suggesting we pull away from this?

or are you concerned about the `AND|OR|NOT` JSON expression of complex logic? FYI I [patched the readme too](https://github.com/ErichBSchulz/api4/blob/e822736cf4e316c6ff049ff426a566d61a9b6a50/readme.md) to illustrate the format

As I mentioned on chat... "you'll be pleased to know that my latest patch will work very fine in an NoSQL world. the QIF/CLIF idea I proposed is something I implemented a complete AND|OR|NOT system without using SQL at all... (PHP array operations and serialised file cache is what drives rocket) " - ie the  `AND|OR|NOT` isn't implementation specific (we could rename it `INTERSECTION|UNION|MINUS` but that would be horrible??)

re security... I've thought about this a fair bit... the critical thing (I hope) is that on every `get()` there needs to be an automatic appending of an `AND [in this user's "$enditiy.$action" ACL]` clause - whether the preceding clauses contain allowable `AND|OR|NOT` should break this logic... should it?? (although I'm wondering about edge cases involving `NOT` (I'm going to open a ticket while I remember)

**Comment by mickadoo** [comment]
I strongly agree with @xurizaemon's concerns. When working on the PHP code it feels like rewriting the [Doctrine query builder](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html#high-level-api-methods) and there's definite overlap between internal services that developers use to manipulate entities and a public API. 

This example from @ErichBSchulz allows for impressive flexibility:

```
$not_first_participant_result =Participant::get()
  ->setSelect(['id'])
  ->addClause(array('NOT',
    array('AND', array(
      array('event_id', '=', $event_id),
      array('contact_id', '=', $contact_id)))))
  ->execute();
```

But at the cost of readability compared to what it would be with Doctrine:

```
$qb->select('p.id')
  ->from('Participant', 'p')
  ->addWhere('p.event_id != :eventId AND p.contact_id != ::contact_id)
```

But Doctrine uses DQL, which was created specifically to allow platform-agnostic SQL-like language. It's goals are different from ours. Developers should be able to create complex queries using SQL-like language. However, I don't agree that all API users should be given the same toolbox. The API usage should be very clear, and that will probably mean limiting features. I'd be interested to see a popular API that allows multiple OR/NOT/AND clauses.

With the OO approach we gain a lot in usability, autocompletion of methods on the request make it clear how to get what you want done. However, by adding methods like `addClause` with a large nested array as an argument we lose some of that clarity.

I would suggest removing the need for such complex OR / NOT requirements for APIv4 and instead focus on enabling them at database level (possibly using an existing library like Doctrine).

**Comment by ecotypes** [comment]
I am a user.  I understand the concerns.  I also know that I've had to resort to a cron job (where I write my own sql) to do a data pull that is impossibly slow using the API as I have access to it.  I need to do a complex join, and the only join that appears to be accessible to me is a very basic simple join.  I can do what I need to do with chaining, but that is beyond slow to usability.  

Before we used CiviCRM, we were in Donor Perfect -- their API let me access any and all data that they deemed to be "ours" -- I only did read-only actions to avoid the potential of clobbering the database, but those actions were done with raw SQL  with the results delivered as XML.  Not fun, but very powerful.  So yes, other systems do allow SQL.

**Comment by mattwire** [comment]
@ecotypes This extension may cover your requirements: https://github.com/systopia/de.systopia.sqltasks

**Comment by ecotypes** [comment]
Thank you.  I will look into that.  An extension would be preferred over the cron job.


Shirley Denton
813-986-6485
ecotypes@verizon.net
On 10/28/2019 9:37:59 AM, Matthew Wire <notifications@github.com> wrote:
@ecotypes [https://github.com/ecotypes] This extension may cover your requirements: https://github.com/systopia/de.systopia.sqltasks [https://github.com/systopia/de.systopia.sqltasks]
