### ISSUE TITLE
Design principles: "Clean" Avoid exposing implementation details

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/org.civicrm.api4#42]
Further to #13 #14 #41, a short braindump of things which I'd like to see addressed more clearly in api4. I'm considering these implications for both internal and external API consumers, and for CiviCRM going forward.

*  #41 - The ability to construct arbitrary / client-driven SQL means that exposed API has to work a lot harder to protect the application performance and data from attackers and bad programming. It also [introduces complexity in other aspects of the API](https://gist.github.com/xurizaemon/27990abd08eb9e93de51a67de88569e7), such as caching.
* #18, #20 - Paging is an essential feature of API queries, but I saw discussion that to expose paging we'd need to expose internal tables which left me uncomfortable. Exposing a new set of (internal) data provides new ways for things to break that an API is supposed to protect against.
* The idea (from chat.civicrm.org) that API queries could pass in cache details feels pretty wrong to me. Maybe I misunderstood the suggestion, but I'd think the application not the client should determine what caching is OK, and offering clients the ability to request outdated cache results has no advantage. I'd feel more OK with clients being able to "force-refresh" a resultset perhaps than for them to pass in a "cache_not_before" param?

Opening this ticket to document a few items that I've seen discussed and where I think it would be good to set a direction on how to approach.

**Comment by ErichBSchulz** [comment]
I think it could be good to open a ticket for:

"Specify cache signature" - would be good to have some focussed conversations on this - 

Isn't the issue with "exposing implementation details" more that we want a [stable API](https://github.com/civicrm/api4/issues/13) - ie it's not that keeping implentation a secret  is a problem - it is more that we need to ensure we don't have to change API signature in the future?

If we have a good pattern that will be friendly for coders that we don't need to change in the future, that is the main thing right? I'm concerned about "dont reveal the implementation" as a goal in itself as often having a thin layer around the "correct" implementation is going to look just like that

**Comment by ErichBSchulz** [comment]
^^^ @xurizaemon does that make any sense at all, or have I misunderstood?

**Comment by xurizaemon** [comment]
Yeah I think you've understood fairly correctly. Ideally what I'm asking is let's have as a goal the API signatures being as clean as possible, without needing people to know about internals. For me this means things like:

* Entities and column names preferring "natural" terminology over than "whatever's in the DB schema"
* Offering paging not requiring exposing a `civicrm_prevnext_cache` entity (IDK, maybe I misunderstood this comment from chat.civicrm.org)
* Encapsulating the query interface to permit filtering without risking security.

**Comment by ErichBSchulz** [comment]
cool!

I think the first one could be it's own case?

yes lets agree forever never to expose any entity with `cache` in it!

re filtering - i *think* we have it nailed - but need to think about harder about #43 

do we need to keep this issue open do you think?
