### ISSUE TITLE
Do we really need the traditional style syntax?

### ISSUE THREAD

**Issue by davialexandre** [civicrm/org.civicrm.api4#58]
What are the advantages of keeping the traditional syntax?

I think this syntax goes against 2 of the Design Principle on the README file:
- **Clean** - leave all the legacy cruft in v3 and start with a clean slate
- **OOP** - use classes in the \Civi namespace - minimize boilerplate via class inheritance/traits

I doesn't look clean to me to have 2 syntaxes for the same thing. Regarding the OOP principle, I understand it's more about the internal classes used by the API than its interface, but I think that, for consistency, it would be better to have a single OOP syntax/interface for the API

**Comment by colemanw** [comment]
Unfortunately yes, we need a non-oop syntax that can be serialized into 
json for non-php uses.

**Comment by davialexandre** [comment]
I don't know exactly how this serialization works, but, to me, it still doesn't seem to be a good enough reason to keep 2 syntaxes for the same thing. We have a lot of API examples in other systems that do have a json syntax  and don't require any non-oop syntax internally.

As I said, I don't know how the serialization works, so here's a question: We need it because it's impossible to do things without it or we need it because some work would be necessary to improve the serialization to not depend on the traditional syntax?

**Comment by colemanw** [comment]
Ok, it's true we don't really need the `civicrm_api4` function in php if that's what you mean.
