### ISSUE TITLE
Add event-driven method to modify api params

### ISSUE THREAD

**Issue by colemanw** [civicrm/org.civicrm.api4#62]
We need a way for each api action to tweak its params without necessitating overriding the parent action.

A/C:

- Event that each api can respond to to format their params on a per-action basis.
- Refactoring code from https://github.com/civicrm/api4/pull/60/files/a5340a524ef2365b84399a0951adc2c6ad40aeab#diff-99ccf38a589eb38555647d760fa495ba

**Comment by mickadoo** [comment]
Agree, using some sort of prepare event would be useful for extension developers too.

**Comment by mickadoo** [comment]
The prepare event already exists and is [fired in the kernel](https://github.com/civicrm/civicrm-core/blob/master/Civi/API/Kernel.php#L258) before running the request. We just need to hook into that. The code @colemanw referenced is for setting default values, are there other requirements for what should be done in the prepare event for this ticket?

**Comment by mickadoo** [comment]
I've started doing some work on this, branching from the open pull request. 

[Here's an example](https://github.com/mickadoo/api4/blob/815933ba6c95e20446055cda51471f9ae3f97c18/Civi/API/Event/Subscriber/CustomGroupPreCreationSubscriber.php) of a subscriber that subscribes to the API prepare event and modifies the [code](https://github.com/civicrm/api4/pull/60/files/a5340a524ef2365b84399a0951adc2c6ad40aeab#diff-99ccf38a589eb38555647d760fa495ba) that @colemanw mentioned.

**Comment by colemanw** [comment]
Is that example for api3 or 4?

**Comment by mickadoo** [comment]
The event driven method to modify parameter is possible in api3 since the prepare event is already part of the core code. The example I linked to in my comment is part of the api4 codebase and is a replacement for the code you mentioned changing in [this comment](https://github.com/civicrm/api4/pull/60/files/a5340a524ef2365b84399a0951adc2c6ad40aeab#r119251655).
