### ISSUE TITLE
CI Testing

### ISSUE THREAD

**Issue by mickadoo** [civicrm/org.civicrm.api4#71]
## Overview

To avoid breaking anything we should run tests automatically on each pull request and show the results in the PR comments.

**Comment by mickadoo** [comment]
I added a travis.yml file in [a branch in my fork](https://github.com/mickadoo/api4/tree/travis) which should be [passing now](https://travis-ci.org/mickadoo/api4/builds/252520477).

There's also this neat sticker I can put in my readme:

![image](https://travis-ci.org/mickadoo/api4.svg?branch=travis)

You can also see the build status in the branch list:

![image](https://user-images.githubusercontent.com/6374064/28158229-f89293d0-67b0-11e7-9b27-8cdc79785138.png)

Or on a pull request with shows the results of a build using the base branch and the pull request:

![image](https://user-images.githubusercontent.com/6374064/28158260-15a520c8-67b1-11e7-8b0a-40cd9b45ff4b.png)

Builds are triggered on any push to any branch. I use a [docker image](https://github.com/mickadoo/civicrm-docker) that I prepared myself as a working CiviCRM environment to run the tests in. It uses CiviCRM master, although this needs to be updated manually whenever tests are run. 

If I had a job running on a server listening for changes to master or new tags in CiviCRM it would be possible to automatically create docker images based on the most recent master or a new tag.

We could then configure Travis to run the tests on different supported versions of CiviCRM using environment variables.

**Comment by colemanw** [comment]
@totten is now working on this.
