### ISSUE TITLE
Return fields with NULL values

### ISSUE THREAD

**Issue by davialexandre** [civicrm/org.civicrm.api4#72]
API v3, has a very unexpected behavior where the response of an Entity.get call won't include fields with `null` values. 

Example: Say you have a custom `Document` entity, with these records:

| id | name  | description    |
|----|-------|----------------|
| 1  | doc 1 | NULL           |
| 2  | doc 2 | Lorem ipsum... |
| 3  | doc 3 | NULL           |

On v3, a call to `Document.get` will return something like

```js
  "values": [
    {
      "id": 1,
      "name": "doc 1",
    },
    {
      "id": 2,
      "name": "doc 2",
      "description": "lorem ipsum..."
    },
    {
      "id": 3,
      "name": "doc 3",
    },
   ]
```

For v4, the fields with `null` values should be returned, so that the previous example would look like this on v4:

```js
  "values": [
    {
      "id": 1,
      "name": "doc 1",
      "description": null,
    },
    {
      "id": 2,
      "name": "doc 2",
      "description": "lorem ipsum..."
    },
    {
      "id": 3,
      "name": "doc 3",
      "description": null
    },
   ]
```

**Comment by colemanw** [comment]
I'm not sure why this behavior is unexpected... it saves bandwidth. Couldn't we just document it?

**Comment by jackrabbithanna** [comment]
Not trying get into a philosophical debate, but if a 'getfields' action says that a property will be in the result set, then one could argue that it should be there, even if NULL...a very meek +1 for inclusion of properties even if the value is NULL .. If the properties returned by a 'getfields' action are considered a contract of some kind then it should be done. Obviously it is easy to work around if you are aware of the behavior, but can require additional effort for downstream developers, especially if you are developing generic wrappers of the CiviCRM api calls, for instance CiviCRM Entity. A property being missing from the call could be interpreted as different meaning than the property being included with value of NULL. Would the API return the property even if NULL, if a 'return' parameter was included in the API call? If that's the case, then perhaps that's ok, because then consumer is specifically asking what properties to receive, and getting what they asked for...

**Comment by davialexandre** [comment]
sorry for the late response. So here are some of the reasons I think null fields should always be returned (unless, of course, you explicitly tell you don't want that field to be included in the response):

- It's an unexpected behaviour. When a dev with a different technical background starts working with CiviCRM, they will expect it to work in a similar way  to the other frameworks and applications they have experience with. Personally, I don't know any other APIs that have this behaviour around null fields, so my expectation was that they would always be returned. It was frustrating to realize this was not the case and it actually resulted in some broken code that had to be fixed later.

- Still talking about unexpected behaviour, there's the fact that the CiviCRM API is a bit schizophrenic, in a sense that it's not clear in which layer it sits on, who should use it and what kind of API it is in the end. Again, as a dev coming with a different technical background, my initial expectation was that the API should only be used via HTTP, in a scenario of an external application needed to communicate with Civi. Soon I realized that I was supposed to use the exact same API also internally, in PHP, while developing extensions and even CiviCRM core itself uses it's API. The "it saves bandwidth" argument only applies to the HTTP scenario.

- In a way, it means that the API is returning partial objects, which leads to more fragile code because it requires many checks to know whether fields can be used or not

**Comment by AkA84** [comment]
> In a way, it means that the API is returning partial objects, which leads to more fragile code because it requires many checks to know whether fields can be used or not

+1

It feels the API is making by default a decision ("don't return any fields with NULL value") that is not its to make, but it should be the developer's

**Comment by omarabuhussein** [comment]
I  also find these two reasons that already mentioned by jackrabbithanna and davialexandre were the most problematic : 

>  especially if you are developing generic wrappers of the CiviCRM api calls, for instance CiviCRM Entity. A property being missing from the call could be interpreted as different meaning than the property being included with value of NULL. 

and 

> In a way, it means that the API is returning partial objects, which leads to more fragile code because it requires many checks to know whether fields can be used or not

**Comment by JoeMurray** [comment]
I think it is better to return values that are Null if they would be returned if the values were non-null.

**Comment by colemanw** [comment]
Ok. I'm convinced.
