### ISSUE TITLE
Have an abstact `Amend` action class extending `Get`

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#8]
Both the current `Delete` and `Update` action classes seem to operate on a `Get` list.

Both contain this boilerplate:

```php
parent::_run($result);       
// Then act on the result    
foreach ($result as $item) { 
  // update it               
}                            
return $result;              
```

Should both `Delete` and `Update` be subclasses of a new abstract "bulk amender" class?

This would allow some batching, queuing, job control magic to be centralised over not just these 2 core actions but also other "update one or more" type actions?

**Comment by colemanw** [comment]
Good idea. It might even be able to support an interactive mode where it says e.g. "75 objects will be deleted. Continue?"

**Comment by ErichBSchulz** [comment]
I guess that would just be a "Count" followed by some kind of `Amend` action on the same set - the issue here is to allow caching so it is performant?

**Comment by JoeMurray** [comment]
Move bulk actions out of PHP and into the db generally improves performance by 10x or more.

**Comment by eileenmcnaughton** [comment]
I agree it performs better in the db - it can bypass hooks though so that is something to bear in mind

**Comment by xurizaemon** [comment]
> Move bulk actions out of PHP and into the db generally improves performance by 10x or more.

If this means "generate updated data in PHP then deliver to DB en masse (or asynchronously)" I'm OK with it. If it means "move business logic to DB layer" I'm uncomfortable with that pattern. (I suspect that latter is NOT what's meant here?)

**Comment by JoeMurray** [comment]
I'm not making a specific proposal at this point. But there may be some kinds of bulk changes that are appropriate to take advantage of the immense performance benefits from this. I don't think it appropriate to move our business logic into SQL. Other brainstorming idea might be to allow PHP business logic to operate on arrays of existing data used for a single object, or to extend use of batch processing and its potential parallelism into other areas especially import and export and deduping.

**Comment by colemanw** [comment]
I've done a lot of reorganizing of the action classes since this issue was opened and I think I've addressed the need. The api performs batch operations in SQL when possible (get) and in PHP when necessary (update, delete).
