### ISSUE TITLE
PHPUnit starts failing after one run

### ISSUE THREAD

**Issue by totten** [civicrm/org.civicrm.api4#80]
@colemanw @mlutfy  When running the `api4` tests locally (`phpunit4 --group headless`), the local build periodically gets stuck generating a bunch of messages like this:

```
PHP Notice:  Undefined index: hu_HU in /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Core/I18n.php on line 210
PHP Stack trace:
PHP   1. {main}() /Users/totten/bknix/civicrm-buildkit/bin/cv:0
PHP   2. require() /Users/totten/bknix/civicrm-buildkit/bin/cv:10
PHP   3. Civi\Cv\Application::main() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/bin/cv:26
PHP   4. Symfony\Component\Console\Application->run() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Application.php:17
PHP   5. Symfony\Component\Console\Application->doRun() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/vendor/symfony/console/Application.php:124
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/vendor/symfony/console/Application.php:193
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/vendor/symfony/console/Application.php:850
PHP   8. Civi\Cv\Command\BootCommand->execute() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/vendor/symfony/console/Command/Command.php:257
PHP   9. Civi\Cv\Command\BootCommand->boot() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Command/BootCommand.php:21
PHP  10. call_user_func:{phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Util/BootTrait.php:46}() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Util/BootTrait.php:46
PHP  11. Civi\Cv\Command\BootCommand->_boot_full() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Util/BootTrait.php:46
PHP  12. Civi\Cv\Bootstrap->boot() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Util/BootTrait.php:100
PHP  13. CRM_Core_Config::singleton() phar:///Users/totten/bknix/civicrm-buildkit/bin/cv/src/Bootstrap.php:194
PHP  14. CRM_Utils_Hook::config() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Core/Config.php:120
PHP  15. CRM_Utils_Hook->invoke() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Hook.php:1165
PHP  16. Civi\Core\CiviEventDispatcher->dispatch() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Hook.php:164
PHP  17. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php:47
PHP  18. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
PHP  19. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
PHP  20. call_user_func:{/Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164}() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
PHP  21. Civi\Core\CiviEventDispatcher::delegateToUF() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
PHP  22. CRM_Utils_Hook_UnitTests->invokeViaUF() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php:86
PHP  23. CRM_Utils_Hook->runHooks() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Hook/UnitTests.php:110
PHP  24. api4_civicrm_config() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Hook.php:270
PHP  25. _api4_civix_civicrm_config() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/ext/api4/api4.php:79
PHP  26. CRM_Core_Smarty::singleton() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/ext/api4/api4.civix.php:17
PHP  27. CRM_Core_Smarty->initialize() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Core/Smarty.php:172
PHP  28. CRM_Core_I18n::languages() /Users/totten/bknix/build/dmaster/sites/all/modules/civicrm/CRM/Core/Smarty.php:154
```

I think the problem is that a bunch of api4 tests  truncate the option-group/option-value tables, and there's [boot-critical code](https://github.com/civicrm/civicrm-core/commit/ece6501cb7994371b48e870294590f23851266e7#diff-777f9a255f83c1af5fe6f854699008c0R166) which expects to find a list of languages in the option-group/option-value tables.

On one hand, truncating those tables feels like playing with fire. On the other hand, updating `CRM/Core/I18n` to grab the language list from file would also that component more predictable/stable. Thoughts?

**Comment by eileenmcnaughton** [comment]
"we have some really crap query writing processes"

https://en.wikipedia.org/wiki/Huhu_beetle#/media/File:Huhu_grubs.jpg

**Comment by colemanw** [comment]
So... playing with fire is bad?
@mickadoo is there an alternative to truncating those tables?

**Comment by mickadoo** [comment]
@colemanw it's been a while, but I think my aim in truncating them was to ensure a completely clean state for some of the tests. I'm guessing the expectations on the tests could be updated to allow for existing records in these tables.

**Comment by totten** [comment]
That sounds like a definite "maybe", @mickadoo.  ;)

There are a few patterns we have for test cleanup, and I think everyone on this thread has seen/used or at least considered some variant of each -- e.g. 

* the truncate-pattern (currently used in api4 tests, but can be overzealous - esp for metadata)
* the transaction-rollback pattern (fast+simple, but not always usable -- breaks on `CREATE TABLE`, etal)
*  the ID-tracking pattern (very general -- works in many contexts -- but sometimes laborious/pain-staking)
* reset the entire db (very general and simple, but also very slow)

```php
// ---- Example of individual ID-tracking - aka the PITA technique -----

function testFoo() {
  $this->foo_id = `INSERT INTO civicrm_option_value ...`;
}
function tearDown() {
  if ($this->foo_id) `DELETE FROM civicrm_option_value WHERE id = $this->fooId`;
}

// ---- Example of ID-tracking by max(id)  ----

function setUp() {
  $this->max_id['civicrm_option_value'] = `SELECT max(id) FROM civicrm_option_value`;
}

function testFoo() {
  `INSERT INTO civicrm_option_value ...`;
}

function tearDown() {
  `DELETE FROM civicrm_option_value WHERE id > $this->max_id['civicrm_option_value']`;
}
```

I think it'd be ideal if we could use the transaction-rollback pattern, but `api4` includes some `CustomField` tests, so there are some tests that won't work with that... the ID-tracking by max(id) might be a gentler transition for this code...?

**Comment by mickadoo** [comment]
@totten you're right, I didn't put too much effort into the answer. I had a look at the failing tests, the one that failed for me isn't using custom data so it probably makes sense that it shouldn't require cleanup on the tables, ideally transaction-rollback should be enough.

My idea for a lot of the tests was to use data sets, similar to doctrine fixtures. This would provide a known state of the database to start off with before running a test. I didn't like the idea that tests would use data created elsewhere, although I can see now that some of the data in the option value tables is required for CiviCRM to work.

I also struggled a bit back then getting the tests working because a lot of my initial stuff with APIv4 was with custom data, so I was a probably a bit muddled and just used what I could to make it work. I did think at the time that tests were able to run multiple times, but it doesn't seem to be the case now.

I agree that transaction-rollback should be the way to go for non-custom value tests. Do you think the transaction pattern should be compatible with loading data sets? I thought I could move the `loadDataSet` calls out of `setUpHeadless` and into `setUp`, so they would be created inside a transaction, but initial attempts to do this had some problems with unknown DB errors. The error was from `DELETE FROM civicrm_cache WHERE group_name = "contact fields" [nativecode=0 **]` which was triggered from inside `CiviTestListener`, maybe I'm just doing something wrong.

I'm not sure if I'll have a lot of time to look into this, I can check with Mike if needed. Seems like if we have all non-custom data tests using transactions instead of truncations, and use the ID tracking for custom data tests it should be a lot cleaner.
