### ISSUE TITLE
Failed upgrade to version 4.1.0

### ISSUE THREAD

**Issue by elijahv** [civicrm/org.civicrm.api4#97]
When attempting to upgrade from version 4.0 to 4.1.0 via the CiviCRM extensions page I received the error 

"Cannot redeclare civicrm_api4() (previously declared in /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/ext/api4/api4.php:19) in /home/vandergiessen/www/www/wp-content/plugins/files/civicrm/custom_ext/org.civicrm.api4/api4.php on line 28"

I'm on CiviCRM 5.5.0 using Wordpress.

**Comment by colemanw** [comment]
Sounds like the extension is installed in two locations. Need to delete one of them.
